
#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define UIP_CONF_ICMP6        1
#define CC2530_RF_CONF_HAS_CC2591 1
#define CC2530_RF_CONF_USE_HGM 1
#define UART0_CONF_WITH_INPUT 1
#define STARTUP_CONF_VERBOSE 1
//#define CC2530_RF_CONF_TX_POWER 0x05

#endif /* PROJECT_CONF_H_ */
